name: Download and split audio

on:
  repository_dispatch:
    types: [download-request]

  workflow_dispatch:
    inputs:
      target_date:
        description: "Target date (YYYY-MM-DD)"
        required: false
        default: "2026-08-05"
      program_id:
        description: "Program ID"
        required: false
        default: "0x13a521a4"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      PROGRAM_ID: "0x13a521a4"
      TARGET_DATE: "2026-08-05"
      # اگر خواستی می‌توانی این را هم عوض کنی
      DL_BASE_PREFIX: "https://dl.telewebion.ir/4eb161fd-c23e-4641-95d5-95dee456df55"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests==2.* pydub==0.* "moviepy==2.*"
          python -c "import moviepy; print('moviepy:', moviepy.__version__)"
          python -c "from moviepy.editor import VideoFileClip; print('VideoFileClip OK')"

      - name: Check moviepy imports
        run: |
          python -c "import moviepy; print('moviepy:', moviepy.__version__)"
          python -c "from moviepy import VideoFileClip; print('VideoFileClip import OK')"


      - name: Run pipeline
        run: |
          python -V
          python -c "import moviepy; from moviepy.editor import VideoFileClip; print('Imports OK')"
          python scripts/pipeline.py


      - name: Upload chunks as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: audio-chunks
          path: |
            work/chunks/chunk_*.mp3
          if-no-files-found: warn
